# Generated by Django 5.2.1 on 2025-05-17 12:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_financialblog_alter_homepage_banner_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialblog',
            name='fin_subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
