# Generated by Django 5.2.1 on 2025-05-17 12:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_financialblog_fin_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialblog',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', 2), ('rich_text', 3), ('simple_rich_text', 4), ('card', 13), ('cta', 18)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your Title', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Add additional text', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('home.blocks.RichTextBlock', (), {}), 4: ('home.blocks.SimpleRichTextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your title', 'required': True}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 8: ('wagtail.blocks.TextBlock', (), {'max_length': 200, 'required': True}), 9: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'If the button page above is selected, that will be used first', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('image', 6), ('title', 7), ('text', 8), ('button_page', 9), ('button_url', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('title', 5), ('cards', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 15: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 16: ('wagtail.blocks.URLBlock', (), {'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'max_length': 40, 'required': True}), 18: ('wagtail.blocks.StructBlock', [[('title', 14), ('text', 15), ('button_page', 9), ('button_url', 16), ('button_text', 17)]], {})}, default='live'),
        ),
    ]
