# Generated by Django 5.2.1 on 2025-05-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_financialblog_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialblog',
            options={'verbose_name': 'Financial Blog', 'verbose_name_plural': 'Financial Blog'},
        ),
    ]
