# Generated by Django 5.2.1 on 2025-05-24 11:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_financialblog_content'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image'),
        ),
        migrations.AlterField(
            model_name='financialblog',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', 2), ('rich_text', 3), ('simple_rich_text', 4), ('card', 13), ('cta', 18), ('codeblock', 21)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your Title', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Add additional text', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('home.blocks.RichTextBlock', (), {}), 4: ('home.blocks.SimpleRichTextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your title', 'required': True}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 8: ('wagtail.blocks.TextBlock', (), {'max_length': 200, 'required': True}), 9: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'If the button page above is selected, that will be used first', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('image', 6), ('title', 7), ('text', 8), ('button_page', 9), ('button_url', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('title', 5), ('cards', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': True}), 15: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 16: ('wagtail.blocks.URLBlock', (), {'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'max_length': 40, 'required': True}), 18: ('wagtail.blocks.StructBlock', [[('title', 14), ('text', 15), ('button_page', 9), ('button_url', 16), ('button_text', 17)]], {}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 20: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 21: ('wagtail.blocks.StructBlock', [[('language', 19), ('code', 20)]], {'classname': 'container', 'label': 'Code block'})}, null=True),
        ),
    ]
