# Generated by Django 5.2.1 on 2025-07-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_newsarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'verbose_name': 'News Article', 'verbose_name_plural': 'News Articles'},
        ),
    ]
