# Generated by Django 5.2.1 on 2025-07-20 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_listing', '0011_newsauthor'),
        ('home', '0023_alter_newsarticle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='news_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog_listing.newsauthor'),
        ),
    ]
