# Generated by Django 5.2.1 on 2025-07-23 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_listing', '0012_alter_newsauthor_options_newsauthor_slug'),
        ('home', '0024_newsarticle_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='news_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='blog_listing.newsauthor'),
        ),
    ]
