# Generated by Django 5.2.1 on 2025-05-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_listing', '0002_myimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
