# Generated by Django 5.2.1 on 2025-05-25 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_listing', '0004_travelbloglistingpage_tutorailsbloglistingpage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TutorailsBlogListingPage',
            new_name='TutorialsBlogListingPage',
        ),
    ]
