# Generated by Django 5.2.1 on 2025-07-15 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_listing', '0005_rename_tutorailsbloglistingpage_tutorialsbloglistingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(choices=[('travel', 'Travel Guides'), ('finance', 'Finance & Budgeting'), ('technology', 'Tech Tutorials'), ('remote-work', 'Remote Work'), ('lifestyle', 'Lifestyle'), ('other', 'Other')], max_length=20)),
                ('article_idea', models.CharField(max_length=200)),
                ('writing_experience', models.TextField()),
                ('writing_samples', models.TextField(blank=True, help_text='Please provide links to your published work (comma separated if multiple)', null=True, validators=[django.core.validators.URLValidator()])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Writer Application',
                'verbose_name_plural': 'Writer Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
