# Generated by Django 5.2.1 on 2025-07-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_listing', '0007_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='Reviewed?'),
        ),
    ]
