# Generated by Django 5.2.1 on 2025-07-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_listing', '0011_newsauthor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsauthor',
            options={'verbose_name': 'News Author', 'verbose_name_plural': 'News Authors'},
        ),
        migrations.AddField(
            model_name='newsauthor',
            name='slug',
            field=models.SlugField(default='other', max_length=200, unique=True),
        ),
    ]
